### ISSUE TITLE
Grey space after Icon

### ISSUE THREAD

**Issue by stuartmemo** [ryanoasis/vim-webdevicons#53] opened 2015-05-21 10:30 UTC
Hey, great plugin! I'm having a little problem where the space inbetween the icon and the label has a grey background. This is probably some colour setting, but I've no idea what to set to change it. Any ideas?

Thanks!

![screen shot 2015-05-21 at 11 23 06](https://cloud.githubusercontent.com/assets/59205/7746736/bbc23712-ffac-11e4-98de-eb5765fd69fa.png)

**Comment by ryanoasis** [comment] 2015-05-21 11:33
I've seen something like this going on in #52 as well.

Can you try to see if setting the follows has any effect on the color:
```vim
let g:webdevicons_conceal_nerdtree_brackets = 0
```

It might be helpful to debug that specific column: http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor

If you can send or show your `vimrc` I can also try to replicate

Thanks

**Comment by stuartmemo** [comment] 2015-05-21 12:18
So the brackets thing removed the colour and I ended up with this.
![screen shot 2015-05-21 at 13 12 30](https://cloud.githubusercontent.com/assets/59205/7748362/a586105e-ffbb-11e4-9aa0-c1e31ca07be6.png)

Using that link you gave me, the cursor says...
`hi<hideBracketsInNerdTree> trans<hideBracketsInNerdTree> lo<hideBracketsInNerdTree>`
That mean anything to you?

My `vimrc` is [here](https://github.com/stuartmemo/vimmy-jones/blob/master/vimrc).

Thanks for helping!

**Comment by ryanoasis** [comment] 2015-05-22 12:10
No problem. There is definitely something going on here. I guess for now that is a workaround but I feel like this is very much solvable (either by me or someone else).

The output doesn't mean too much to me yet but definitely seems to have to do with the custom bracket hide syntax.

Thanks for the vimrc link, I will see what I can do to replicate and hopefully fix.

**Comment by ryanoasis** [comment] 2015-06-02 22:56
@stuartmemo can you tell me if it is the same regardless of `vim` or `gvim` ? And which are the screenshots from?

Sorry but also can you tell me the exact font you are using?

I tested with your `vimrc` even after installing the same plugins. I tested with Droid Sans patched and Droid Sans (true Mono) patched and could not replicate :disappointed: 

![selection_02_06_15_18 48 57_1018x742_001](https://cloud.githubusercontent.com/assets/8083459/7949136/0eccb670-0959-11e5-87f8-cbdae6e16351.png)

**Comment by ryanoasis** [comment] 2015-06-02 23:04
@stuartmemo My bad! I just got this issue. I was only doing `PluginInstall` instead of `PluginUpdate` so when updated to version 4.0.2 I can now see the issue!

![selection_02_06_15_19 04 39_202x218_001](https://cloud.githubusercontent.com/assets/8083459/7949267/3b8c68d0-095a-11e5-811c-77d652fb6fd9.png)

**Comment by ryanoasis** [comment] 2015-06-02 23:19
I had a few hunches and I think I have a fix for this but not really 100% sure why it fixes it

Changing this:
```vim
autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal cchar=  containedin=ALL
```
to:
```vim
autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=ALL
```

seems to solve the issue. From what I understand though not explicitly setting the `cchar` sets it to a space by default

**Comment by stuartmemo** [comment] 2015-06-03 09:56
Ah, amazing! That worked a treat.

The icons are quite tight with the text though now, it was quite nice having a bit more space. I know, never happy :frog: 

![screen shot 2015-06-03 at 10 50 51](https://cloud.githubusercontent.com/assets/59205/7957428/398c01aa-09df-11e5-8d86-bf1e3de21ef8.png)

**Comment by ryanoasis** [comment] 2015-06-03 12:39
@stuartmemo 

1. Great to know it worked for you as well.

2. About the tightness that is actually configurable :wink: 

Per the readme:
the amount of space to use after the glyph character (default ' ')
```vim
let g:WebDevIconsNerdTreeAfterGlyphPadding = '  '
```

**Comment by stuartmemo** [comment] 2015-06-03 14:08
@ryanoasis You rule the school. Thank you so much.

**Comment by kristijanhusak** [comment] 2015-06-05 12:53
Hi,

I'm having the same bug. It is caused by `Conceal` highlighting in the color scheme.

Adding
```
hi Conceal guibg=NONE
```
To vimrc solves the issue.

**Comment by ryanoasis** [comment] 2015-06-06 13:04
@kristijanhusak Thanks, yeah I believe the `autocmd` change will fix it. Just to confirm did the `autocmd` change I posted work for you?

If not I will at least add your fix as a possibility on the readme.

**Comment by kristijanhusak** [comment] 2015-06-06 17:32
@ryanoasis Yes, autocmd works for me, and as i said, it's better solution because of colors with cursorline. 
You could add it if you want as an alternative solution, if autocmd does not work for someone.

**Comment by ryanoasis** [comment] 2015-06-15 18:31
fixed/completed with latest release

**Closed by ryanoasis** 2015-06-15 18:31 UTC
Labels: confirmed-bug
